### ISSUE TITLE
Can't input OpenAI API key on GUI

### ISSUE THREAD

**Issue by menenemi** [takanotume24/Cuuri#112]
When I open the app for the first time, I can't input API key on the GUI, and I can't even focus the "Enter your OpenAI API key" input bar.
If I input the API key into the `openai_api_key` env variable in `~/.cuuri/config.toml` and restart the app, I can normally use this app.

Cuuri version: 0.2.1 (20241207.113544)
OS version: macOS Sequoia 15.1

**Comment by takanotume24** [comment]
Thank you for the report! I think there’s likely an issue with the dialog display. I have written instructions in the README to edit the config file directly. Right now, I'm using `v-if` to forcefully display the API key registration dialog, but I believe it would be better to route it to a separate page instead.

**Comment by takanotume24** [comment]
This issue was addressed by #124. I separated the settings screen into a different page using vue-router. I believe this resolves the problem. This fix is scheduled to be released in version 2.2.

**Comment by menenemi** [comment]
It works fine now! Thank you for the fix!
