### ISSUE TITLE
Make build instructions more user friendly 

### ISSUE THREAD

**Issue by menenemi** [takanotume24/Cuuri#113]
When I followed the build instructions, I encountered a problem as shown below:
```bash
🍡dex@:~/src/github.com/Cuuri$ npm run tauri build

> cuuri@0.2.1 tauri
> tauri build

sh: tauri: command not found
```

I had to run `npm i` command before running `npm run tauri build`(step 3) for successful build.
I think it’s a good idea to write something about it for making this app build process more user friendly!

**Comment by takanotume24** [comment]
Thanks for the comment! I've added it to the README.
